services:
  web:
    build: .
    image: gtxvii/nameofyourappss:1.0
    ports:
      - "3001:8080"
    
  DB:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: testdatabase
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: